apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox
  labels:
    app: myapp
    type: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5