apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    app: myapp
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  tolerations:
  - key: spray
    Value: mortein
    effect: NoSchedule