apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: myapp
    tier: backend
spec:
  containers:
  - name: mysql
    image: mysql:5.7

  envFrom:
  - secretRef:
    - name: db-secret
   