apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi  
  volumes:
  - name: vol
    hostPath:
      path: /pv/log
  persistentVolumeReclaimPolicy: Recycle