apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: myapp
    tier: backend
spec:
  containers:
  - name: redis
    image: redis
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c','sleep 20'] 