apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
  labels:
    app: myapp
    tier: backend
spec:
  containers:
  - name: volume-container-datacenter-1
    image: centos:latest
    command: ['/bin/bash', '-c','sleep 10000'] 
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/news
  - name: volume-container-datacenter-2
    image: centos:latest
    command: ['/bin/bash', '-c','sleep 10000'] 
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/cluster
  volumes:
  - name: volume-share
    emptyDir: {}
    