apiVersion: v1
kind: Pod
metadata:
  name: webapp
  
spec:
  restartPolicy: Never
  volumes:
  - name: my-vol
    PersistentVolumeClaim:
    claimName: claim-log-1
  containers:
  - name: nginx
    image: nginx
    
    volumeMounts:
    - name: my-vol
      mountPath: /var/log/nginx
